# Use Node.js base image
FROM node:22.14.0

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the client files
COPY . .

# Expose React development server port
EXPOSE 5173

# Run in development mode
CMD ["npm", "run", "dev"]