version: "3.8"

services:
  server:
    build: ./server
    container_name: meetbot_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: ${MONGO_URL} 
      GROQ_API_KEY: ${GROQ_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-auth.json
    volumes:
      - ./server:/app
      - ./secrets/meetbot-452507-5fae99c8df76.json:/app/google-auth.json
    
  client:
    build: ./client
    container_name: meetbot_client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app