# Use Node.js base image
FROM node:22.14.0

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN rm -rf node_modules package-lock.json && npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the client files
COPY . .

# Expose the server port
EXPOSE 8000

# Run the server using nodemon
CMD ["nodemon", "index.js"]